write exit message to stderr

diff --git a/utils/sdboot-mkconfig b/utils/sdboot-mkconfig
--- a/utils/sdboot-mkconfig
+++ b/utils/sdboot-mkconfig
@@ -105,7 +105,7 @@ function remove_entry {
       exit 1
     fi
   else
-    echo "ERROR: Cannot remove default entry ${KERNEL@Q}."
+    echo "ERROR: Cannot remove default entry ${KERNEL@Q}." >&2
     exit 1
   fi
 }
